server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/marinazv/examen-esp-backend-ZuritaVerzini-Marina-ConfigServer
          default-label: main
          force-pull: true


